version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  shaka-packager:
    image: google/shaka-packager:latest
    container_name: shaka-packager
    entrypoint: [ "tail", "-f", "/dev/null" ] # Keeps container running
    volumes:
      - ./videos:/videos  # Shared folder for input/output
    restart: unless-stopped

volumes:
  minio-data:
  mongo-data:
